add review
nkhs-ha05hc42/hc42-1002-git-work4-1 pull request #1
Opened 2024-11-18 03:02 UTC by hc421002

2024-11-18 03:11 UTC, harusamewktk requested changes
レビューしました！
コメント箇所をご確認ください。

2024-11-18 03:11 UTC, harusamewktk commented on review.txt
> +review test1
1行目と2行目を入れ替えてください

2024-11-25 01:10 UTC, hc421002 commented
@harusamewktk 
修正しました。

2024-11-25 02:11 UTC, harusamewktk approved these changes
修正確認しました!
LGTM!!

2024-11-25 02:28 UTC, merged